### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Geogliff**

### CODE REVIEW

**Comment by seht** [comment]
That's perfect. thank you for contributing! :)

Before I can merge. Could you please change the file path (so that it does not replace the current base file), creating a new folder a level above with the language code suffix (e.g. ../values-cz/strings.xml

Thank you!

Thank you! :)

**Comment by Geogliff** [comment]
Is it fine now?

**Comment by seht** [comment]
You would have to change the folder and recommit it and submit a new pull request! ^^

**Comment by seht** [comment]
make you do a git pull first! :) then git add -A (before git commit) ^^

**Comment by Geogliff** [comment]
Well, would you be okay with just sending the file itself then? :( I
apologize, I just wanted to support your app, but as you can see, I'm
pretty bad at things like GitHub, although I appreciate your try to help me
and having patience with me.
Thank you.

**Comment by seht** [comment]
Hey, sure thing thing. No problem at all. Just let me know what attribution you would like me to refer (like a link to your page or such) and I'll do it for you. :) Thank you!

**Comment by Geogliff** [comment]
Just some reference to my nickname Geogliff would be enough.
Thank you for your app, glad I could support it some way and have a nice
day!

On Mon, Feb 6, 2017, 23:48 Seht <notifications@github.com> wrote:

Hey, sure thing thing. No problem at all. Just let me know what attribution
you would like me to refer (like a link to your page or such) and I'll do
it for you. :) Thank you!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/seht/volumenotification/pull/8#issuecomment-277839936>,
or mute the thread

**Comment by Geogliff** [comment]
And a small suggestion - what do you think about adding a separate button
for turning vibration on and off?

**Pull request closed without merging**
